import MyAuth from 'auth';
import MyConverter from 'converter';
import MyDao from 'dao';
import MyFilter from 'filter';
import * as I from 'interfaces';
import { Container } from 'inversify';
import MyLimiter from 'limiter';
import MyServer from 'server';
import MyService from 'service';
import TYPES from 'Types';

const container = new Container();
container.bind<I.Service>(TYPES.Service).to(MyService).inSingletonScope();
container.bind<I.Dao>(TYPES.Dao).to(MyDao).inSingletonScope();
container.bind<I.Server>(TYPES.Server).to(MyServer).inSingletonScope();
container.bind<I.Auth>(TYPES.Auth).to(MyAuth).inSingletonScope();
container.bind<I.Filter>(TYPES.Filter).to(MyFilter).inSingletonScope();
container.bind<I.Limiter>(TYPES.Limiter).to(MyLimiter).inSingletonScope();
container.bind<I.Converter>(TYPES.Converter).to(MyConverter).inSingletonScope();
export default container;
